### ISSUE TITLE
Cotton not working.  

### ISSUE THREAD

**Issue by JonCaver** [ShangguanXi/RusticDelight-Refabricated#5] opened 2024-10-21 00:21 UTC
So idk if there is a problem with your port but none you the cotton is working for me. 
other then the wild spawning in the world.
when you harvest it you get no drops. also when you plant a seed {acquired in creative then planted in survival) when it grows up that doesn't drop anything either when you harvest the cotton you grow.

**Comment by ShangguanXi** [comment] 2024-10-21 03:55
I cant reproduce this bug.

**Comment by JonCaver** [comment] 2024-10-21 05:49
is there a dependency besides the original farmers delight for fabric that you are using for this? or a resource pack?

**Comment by 2190303755** [comment] 2024-10-21 06:59
this mod requires Farmer's Delight Refabricated instead of Farmer's Delight which has been achieved

**Comment by JonCaver** [comment] 2024-10-21 16:46
correct that is only one that works for fabric. I have that on the latest version and your mod. very strange that it is working for you and not me.

**Comment by JonCaver** [comment] 2024-10-21 17:10
thanks for trying. looks like im still stuck to sugarcane for paper like everyone else. haha

**Comment by ShangguanXi** [comment] 2024-10-22 13:22
ok, 1.21.1 have this bug, it will be fixed on next version

**Comment by ShangguanXi** [comment] 2024-10-22 13:44
fixed

**Closed as completed** 2024-10-22 13:46 UTC
Labels: bug
